Demo.PL/ViewModels/RoleViewModel.cs
namespace Demo.PL.ViewModels
{
    public class RoleViewModel
    {
        public string Id { get; set; }
        public string RoleName { get; set; }
    }
}

Demo.PL/Controllers/RoleController.cs
using AutoMapper;
using Demo.DAL.Models;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;

        //inject from user manager
        public RoleController(RoleManager<IdentityRole> roleManager, IMapper mapper,UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _mapper = mapper;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(string SearchInput)
        {
            var users = Enumerable.Empty<RoleViewModel>();
            if (string.IsNullOrEmpty(SearchInput))
            {
                users = await _roleManager.Roles.Select(R => new RoleViewModel()
                {
                    Id = R.Id,
                    RoleName = R.Name,
                }).ToListAsync();

            }
            else
            {
                users = await _roleManager.Roles.Where(U => U.Name.ToLower()
                                                .Contains(SearchInput.ToLower()))
                                                .Select(R => new RoleViewModel()
                                                {
                                                    Id = R.Id,
                                                    RoleName = R.Name,
                                                }).ToListAsync();

            }

            return View(users);

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid) // Server Side Validation
            {

                var Role = new IdentityRole()
                {
                    Name = model.RoleName,
                };
                await _roleManager.CreateAsync(Role);
                return RedirectToAction(nameof(Index));

            }
            return View(model);
        }
        public async Task<IActionResult> Details(string? id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var roleFromDb = await _roleManager.FindByIdAsync(id);
            if (roleFromDb is null)
                return NotFound();

            var user = new RoleViewModel()
            {
                Id = roleFromDb.Id,
                RoleName = roleFromDb.Name
            
            };
            return View(ViewName, user);
        }

        public async Task<IActionResult> Edit(string? id)
        {
            return await Details(id, "Edit");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, RoleViewModel model)
        {
            if (id != model.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                var userFromDb = await _roleManager.FindByIdAsync(id);
                if (userFromDb is null)
                    return NotFound();
                userFromDb.Id = model.Id;
                userFromDb.Name = model.RoleName;
                await _roleManager.UpdateAsync(userFromDb);
                return RedirectToAction(nameof(Index));

            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            return await Details(id, "Delete");


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, UserViewModel model)
        {
            if (id != model.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                var userFromDb = await _roleManager.FindByIdAsync(id);
                await _roleManager.DeleteAsync(userFromDb);
                return RedirectToAction(nameof(Index));

            }
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
                return NotFound();
            ViewData[index: "RoleId"] = roleId;
            var usersInRole = new List<UserInRoleViewModel>();
            var users = await _userManager.Users.ToListAsync();
            foreach (var user in users)
            {
                var userInRole = new UserInRoleViewModel()
                {
                    UserId = user.Id,

                    UserName = user.UserName
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userInRole.IsSelected = true;
                }
                else
                {
                    userInRole.IsSelected = false;
                }
                usersInRole.Add(userInRole);
            }
            return View(usersInRole);
        }



        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId,List<UserInRoleViewModel> users)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
                return NotFound();
            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appUser =await _userManager.FindByIdAsync(user.UserId);
                    if(appUser is not null)
                    {
                        if (user.IsSelected == true && !await _userManager.IsInRoleAsync(appUser, role.Name)) 
                        {
                            await _userManager.AddToRoleAsync(appUser, role.Name);
                        }
                        else if(!user.IsSelected == true && await _userManager.IsInRoleAsync(appUser, role.Name))
                        {
                            await _userManager.RemoveFromRoleAsync(appUser, role.Name);
                        }
                    }
                }
                return RedirectToAction(nameof(Edit), new { id = roleId });
            }

            return View(User);
        }
    }
}

Demo.PL/Controllers/UserController.cs
using AutoMapper;
using Demo.DAL.Models;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace Demo.PL.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;

        //inject from user manager
        public UserController(UserManager<ApplicationUser> userManager,IMapper mapper)
        {
            _userManager = userManager;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(string SearchInput)
        {
            var users=Enumerable.Empty<UserViewModel>();
            if (string.IsNullOrEmpty(SearchInput))
            {
                users =await _userManager.Users.Select(U => new UserViewModel()
                {
                    Id = U.Id,
                    FName = U.FirstName,
                    LName = U.LastName,
                    Email = U.Email,
                    Roles = _userManager.GetRolesAsync(U).Result
                }).ToListAsync();

            }
            else
            {
                users = await _userManager.Users.Where(U=>U.Email.ToLower()
                                                .Contains(SearchInput.ToLower()))
                                                .Select(U => new UserViewModel()
                {
                    Id = U.Id,
                    FName = U.FirstName,
                    LName = U.LastName,
                    Email = U.Email,
                    Roles = _userManager.GetRolesAsync(U).Result
                }).ToListAsync();

            }

            return View(users);
           
        }

        public async Task<IActionResult> Details(string? id,string ViewName="Details") 
        {
            if (id is null)
                return BadRequest();
            var userFromDb = await _userManager.FindByIdAsync(id);
            if (userFromDb is null)
                return NotFound();

            var user = new UserViewModel()
            {
                Id = userFromDb.Id,
                FName = userFromDb.FirstName,
                LName = userFromDb.LastName,
                Email = userFromDb.Email,
                Roles = _userManager.GetRolesAsync(userFromDb).Result
            };
            return View(ViewName,user);
        }

        public async Task<IActionResult> Edit(string? id)
        {
            return await Details(id, "Edit");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, UserViewModel model)
        {
            if(id != model.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                var userFromDb =await _userManager.FindByIdAsync(id);
                if(userFromDb is null)
                    return NotFound();
                userFromDb.FirstName = model.FName;
                userFromDb.LastName=model.LName;
                await _userManager.UpdateAsync(userFromDb);
                return RedirectToAction(nameof(Index));
            
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            return await Details(id, "Delete");


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, UserViewModel model)
        {
            if (id != model.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                var userFromDb = await _userManager.FindByIdAsync(id);
                await _userManager.DeleteAsync(userFromDb);
                return RedirectToAction(nameof(Index));

            }
            return View(model);
        }


    }
}

Demo.PL/Views/Role/AddOrRemoveUsers.cshtml
@model List<UserInRoleViewModel>

@{
    ViewData["Title"] = "AddOrRemoveUsers";
    var RoleId = ViewData["RoleId"] as string;
}


<form asp-action="AddOrRemoveUsers" asp-route-roleId="@RoleId">

    @for (int i = 0; i < Model.Count; i++)
    {
        <div class="form-group">

            <input asp-for="@Model[i].IsSelected" />

            <label asp-for="@Model[i].IsSelected">@Model[i].UserName</label>

        </div>

        <input type="hidden" asp-for="@Model[i].UserId"/>

        <input type="hidden" asp-for="@Model[i].UserName"/>
        
    }

    <input type="submit" value="Update" class="btn btn-success"/>

    <a asp-action="Edit" asp-route-id="@RoleId" class="btn btn-light"> Cancel</a>

</form>

Demo.PL/Views/Role/Create.cshtml
@model RoleViewModel

@{
    ViewData["Title"] = "Create";

}

<div class="container">
    <h1> Create Department </h1>

    <br />



    <form asp-action="Create">
        <partial name="RolePartialView/_EditCreateRole" model="Model" />
        <input type="submit" value="Create" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-light">Back To List</a>

    </form>


</div>

Demo.PL/Views/Role/Delete.cshtml
@model RoleViewModel


@{
    ViewData["Title"] = "Delete";

}

<div class="container">
    <h1>Delete Department </h1>

    <br />


    <form asp-action="Delete">

        <partial name="RolePartialView/_DeleteDetailsRole" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-controller="User" asp-action="Index" class="btn btn-light">Back To List</a>

    </form>
</div>>

Demo.PL/Views/Role/Details.cshtml
@model RoleViewModel
@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <h1>Department Details</h1>

    <br />

    <div>
        <partial name="RolePartialView/_DeleteDetailsRole" />
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a>
        <a asp-action="Index" class="btn btn-secondary">Back To List</a>
    </div>


</div>

Demo.PL/Views/Role/Edit.cshtml
@model RoleViewModel

@{
    ViewData["Title"] = "Edit";
}
<div class="container">

    <h1> Edit Department </h1>

    <br />



    <form asp-action="Edit">
        <partial name="RolePartialView/_EditCreateRole" model="Model" />

        @* <button asp-action="AddOrRemoveUser" asp-route-RoleId="@Model.Id" asp-controller="Role" class="ResetPassword btn">Add Or Remove User</button> *@
        <a asp-action="AddOrRemoveUsers" asp-route-roleId="@Model.Id" class="my-3 btn btn-success"> Add Or Remove Users  </a>

        <input type="submit" value="Save" class="btn logOutBtn" />
        <a asp-action="Index" class="btn btn-dark">Back To List</a>

    </form>


</div>

Demo.PL/Views/Role/Index.cshtml
@model IEnumerable<RoleViewModel>
@{
    ViewData["Title"] = "Index";
}


<div class="container">
    <h1>All Roles</h1>

    <form class="d-flex" asp-action="Index">
        <input type="search" placeholder="Search.........." name="SearchInput" id="SearchInput" class="form-control my-3" />

        <div>
            <button class="btn btn-outline-success  my-3 mx-2" type="submit">Search...</button>
        </div>
    </form>

    <a asp-action="Create" class="btn btn-primary"> Create Role</a>


    <br />
    <br />

    @if (Model.Count() > 0)
    {

        <table class="table table-striped table-hover table-bordered text-center">

            <thead>

                <tr>

                    <th> @Html.DisplayNameFor(D => D.Id) </th>
                    <th> @Html.DisplayNameFor(D => D.RoleName) </th>
                    <th> Details </th>
                    <th> Update </th>
                    <th> Delete </th>

                </tr>

            </thead>


            <tbody>

                @foreach (var user in Model)
                {
                    <tr>
                        <td>@user.Id</td>
                        <td>@user.RoleName</td>
                        <partial name="_ButtonPartialView" model="@user.Id" />

                    </tr>
                }

            </tbody>

        </table>

    }

    else
    {

        <div class=" mt-4 alert alert-danger">
            <h3> There Is No Roles :( </h3>
        </div>


    }
</div>